import "server-only";

import * as localStore from "@/services/requirement/local-store";

export type PublishRequirementInput = localStore.PublishRequirementInput;
export type CreateProjectInput = localStore.CreateProjectInput;
export type UpdateProjectInput = localStore.UpdateProjectInput;
export type RequirementKnowledgeMatch = localStore.RequirementKnowledgeMatch;
export type RequirementKnowledgeScope = localStore.RequirementKnowledgeScope;
export type RequirementReleaseFact = localStore.RequirementReleaseFact;
export type RequirementReleaseStatus = localStore.RequirementReleaseStatus;
export type RequirementTimelineView = localStore.RequirementTimelineView;
export type RequirementTimelinePage = localStore.RequirementTimelinePage;
export type CurrentRequirementKnowledgeSource = localStore.CurrentRequirementKnowledgeSource;
export type UpdateRequirementReleaseStatusInput = localStore.UpdateRequirementReleaseStatusInput;
export type RequirementTestCase = import("@/lib/types").RequirementTestCase;

export const listProjects = localStore.listProjects;
export const createProject = localStore.createProject;
export const updateProject = localStore.updateProject;
export const archiveProject = localStore.archiveProject;
export const restoreProject = localStore.restoreProject;
export const getProject = localStore.getProject;
export const getRequirementDetail = localStore.getRequirementDetail;
export const listProjectRequirements = localStore.listProjectRequirements;
export const archiveRequirement = localStore.archiveRequirement;
export const restoreRequirement = localStore.restoreRequirement;
export const updateRequirementReleaseStatus = localStore.updateRequirementReleaseStatus;
export const listRequirementTimeline = localStore.listRequirementTimeline;
export const listVersions = localStore.listVersions;
export const getVersion = localStore.getVersion;
export const listComments = localStore.listComments;
export const listRequirementGaps = localStore.listRequirementGaps;
export const addRequirementGap = localStore.addRequirementGap;
export const listVersionTestCases = localStore.listVersionTestCases;
export const findRelevantTestCases = localStore.findRelevantTestCases;
export const replaceVersionTestCases = localStore.replaceVersionTestCases;
export const updateVersionTestCaseStatus = localStore.updateVersionTestCaseStatus;
export const getTestCaseGenerationContext = localStore.getTestCaseGenerationContext;
export const searchRequirements = localStore.searchRequirements;
export const listCurrentRequirementKnowledgeSources = localStore.listCurrentRequirementKnowledgeSources;
export const findRequirementKnowledge = localStore.findRequirementKnowledge;
export const findScopedRequirementKnowledge = localStore.findScopedRequirementKnowledge;
export const listScopedRequirementReleaseFacts = localStore.listScopedRequirementReleaseFacts;
export const addComment = localStore.addComment;
export const uploadArtifact = localStore.uploadArtifact;
export const publishRequirement = localStore.publishRequirement;
export const publishRequirementSnapshot = localStore.publishRequirementSnapshot;
export const downloadRequirementVersion = localStore.downloadRequirementVersion;
export const restoreRequirementVersion = localStore.restoreRequirementVersion;
