"use client";

import { useEffect, useRef, useState } from "react";
import { Icon } from "@/components/icons";
import type { HtmlCommentAnchor, RequirementComment } from "@/lib/types";

type FrameSelection = { anchor: HtmlCommentAnchor; left: number; top: number };
type Actor = { id?: string; name: string; initial: string };
const BRIDGE = "requirement-demo-comment";

const demoCommentBridge = String.raw`(() => {
  const bridge = ${JSON.stringify(BRIDGE)};
  let commentMode = false; let hovered = null; let markers = [];
  const markerClass = "rp-demo-comment-marker", hoverClass = "rp-demo-comment-hover", selectedClass = "rp-demo-comment-selected";
  const post = (type, payload = {}) => parent.postMessage({ bridge, type, ...payload }, "*");
  const escape = (value) => window.CSS && CSS.escape ? CSS.escape(value) : value.replace(/[^a-zA-Z0-9_-]/g, "\\$&");
  const selectorFor = (element) => { if (element.id) return "#" + escape(element.id); const parts = []; let current = element; while (current && current.tagName !== "BODY" && parts.length < 6) { const tag = current.tagName.toLowerCase(); const siblings = current.parentElement ? Array.from(current.parentElement.children).filter((item) => item.tagName === current.tagName) : []; parts.unshift(tag + (siblings.length > 1 ? ":nth-of-type(" + (siblings.indexOf(current) + 1) + ")" : "")); current = current.parentElement; } return parts.join(" > "); };
  const targetFor = (target) => { if (!(target instanceof Element) || target.closest("." + markerClass)) return null; const element = target.closest("button,a,input,textarea,select,article,section,li,td,th,div,p,h1,h2,h3,h4,h5,h6,img") || target; return element && element.tagName !== "BODY" && element.tagName !== "HTML" ? element : null; };
  const clearHovered = () => { if (hovered) hovered.classList.remove(hoverClass); hovered = null; };
  const clearMarkers = () => { document.querySelectorAll("." + markerClass).forEach((node) => node.remove()); };
  const isVisible = (target) => { if (!target || !target.getClientRects().length) return false; const rect = target.getBoundingClientRect(); if (rect.width <= 0 || rect.height <= 0 || rect.right <= 0 || rect.bottom <= 0 || rect.left >= window.innerWidth || rect.top >= window.innerHeight) return false; let current = target; while (current && current.nodeType === 1) { const computed = getComputedStyle(current); if (computed.display === "none" || computed.visibility === "hidden" || Number(computed.opacity) === 0) return false; current = current.parentElement; } const x = Math.max(0, Math.min(window.innerWidth - 1, rect.left + Math.min(rect.width / 2, window.innerWidth - rect.left - 1))); const y = Math.max(0, Math.min(window.innerHeight - 1, rect.top + Math.min(rect.height / 2, window.innerHeight - rect.top - 1))); const hit = document.elementFromPoint(x, y); return Boolean(hit && (hit === target || target.contains(hit))); };
  const hostFor = (target) => { let host = target.parentElement; while (host && host !== document.body) { if (getComputedStyle(host).position !== "static") return host; host = host.parentElement; } return document.body; };
  const renderMarkers = () => { clearMarkers(); markers.forEach((comment) => { const target = document.querySelector(comment.selector); const content = (target?.getAttribute("aria-label") || target?.textContent || "").replace(/\s+/g, " ").trim(); if (!target || !isVisible(target) || (comment.quote && !content.includes(comment.quote.slice(0, 80)))) return; const rect = target.getBoundingClientRect(); const marker = document.createElement("button"); marker.type = "button"; marker.className = markerClass; marker.textContent = (comment.initial || "评").slice(0, 1); marker.style.left = (rect.right - 11) + "px"; marker.style.top = (rect.top - 11) + "px"; const position = { left: rect.left, right: rect.right, top: rect.top, bottom: rect.bottom }; marker.addEventListener("mouseenter", () => post("marker-hover", { id: comment.id, ...position })); marker.addEventListener("mouseleave", () => post("marker-leave")); marker.addEventListener("click", (event) => { event.preventDefault(); event.stopPropagation(); post("marker-click", { id: comment.id, ...position }); }); document.body.append(marker); }); };
  const style = document.createElement("style"); style.textContent = ".rp-demo-comment-mode *{cursor:url('data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%2224%22 height=%2224%22%3E%3Cpath d=%22M3 4a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H11l-5 5v-5H6a3 3 0 0 1-3-3V4z%22 fill=%22%233370ff%22/%3E%3Cpath d=%22M7 8h10M7 12h7%22 stroke=%22white%22 stroke-width=%222%22 stroke-linecap=%22round%22/%3E%3C/svg%3E') 4 20,crosshair!important}." + hoverClass + "{outline:1px dashed #3370ff!important;outline-offset:-1px!important}." + selectedClass + "{outline:2px solid #3370ff!important;outline-offset:-2px!important}." + markerClass + "{position:fixed!important;z-index:2147483647!important;display:grid!important;width:22px!important;height:22px!important;place-items:center!important;border:2px solid #fff!important;border-radius:50%!important;padding:0!important;color:#fff!important;background:#f79009!important;box-shadow:0 2px 7px rgba(16,24,40,.18)!important;font:700 10px sans-serif!important;cursor:pointer!important}"; document.head.append(style);
  document.addEventListener("mousemove", (event) => { if (!commentMode) return; const next = targetFor(event.target); if (next === hovered) return; clearHovered(); if (next) { hovered = next; next.classList.add(hoverClass); } }, true);
  document.addEventListener("click", (event) => { if (!commentMode) return; const target = targetFor(event.target); if (!target) return; event.preventDefault(); event.stopPropagation(); clearHovered(); document.querySelectorAll("." + selectedClass).forEach((node) => node.classList.remove(selectedClass)); target.classList.add(selectedClass); const rect = target.getBoundingClientRect(); const quote = (target.getAttribute("aria-label") || target.textContent || target.tagName).replace(/\\s+/g, " ").trim().slice(0, 500); post("selection", { selector: selectorFor(target), quote, x: rect.left + window.scrollX, y: rect.top + window.scrollY, width: rect.width, height: rect.height, viewportLeft: rect.left, viewportBottom: rect.bottom }); }, true);
  window.addEventListener("scroll", renderMarkers, { passive: true }); window.addEventListener("resize", renderMarkers, { passive: true });
  const observer = new MutationObserver((records) => { if (records.length && records.every((record) => record.type === "childList" && Array.from(record.addedNodes).concat(Array.from(record.removedNodes)).every((node) => node.nodeType === 1 && node.classList.contains(markerClass)))) return; window.requestAnimationFrame(renderMarkers); }); observer.observe(document.documentElement, { childList: true, subtree: true, attributes: true, attributeFilter: ["class", "style", "hidden", "aria-hidden"] });
  window.addEventListener("message", (event) => { const data = event.data; if (!data || data.bridge !== bridge) return; if (data.type === "mode") { commentMode = Boolean(data.value); document.documentElement.classList.toggle("rp-demo-comment-mode", commentMode); if (!commentMode) clearHovered(); } if (data.type === "markers") { markers = Array.isArray(data.items) ? data.items : []; renderMarkers(); } if (data.type === "clear-selection") document.querySelectorAll("." + selectedClass).forEach((node) => node.classList.remove(selectedClass)); });
  post("ready");
})();`;

function roots(comments: RequirementComment[]) { return comments.filter((comment) => !comment.parentId && comment.anchor && "selector" in comment.anchor && !comment.deletedAt); }
function injectBridge(html: string, src: string) { const base = src.slice(0, src.lastIndexOf("/") + 1).replace(/"/g, "%22"); const withBase = /<head\b[^>]*>/i.test(html) ? html.replace(/<head\b[^>]*>/i, (head) => `${head}<base href="${base}">`) : `<base href="${base}">${html}`; const bridge = `<script>${demoCommentBridge.replace(/<\/script/gi, "<\\/script")}</script>`; return /<\/body>/i.test(withBase) ? withBase.replace(/<\/body>/i, `${bridge}</body>`) : `${withBase}${bridge}`; }
function bubblePosition(frameRect: DOMRect, data: Record<string, unknown>, height: number) {
  const gap = 10;
  const width = 306;
  const leftEdge = frameRect.left + Number(data.left);
  const rightEdge = frameRect.left + Number(data.right);
  const topEdge = frameRect.top + Number(data.top);
  const preferredLeft = rightEdge + gap;
  const left = preferredLeft + width <= window.innerWidth - gap ? preferredLeft : leftEdge - width - gap;
  return { left: Math.max(gap, Math.min(left, window.innerWidth - width - gap)), top: Math.max(gap, Math.min(topEdge, window.innerHeight - height - gap)) };
}

function isOwner(comment: RequirementComment, actor: Actor) {
  return comment.authorId ? comment.authorId === actor.id : comment.author === actor.name;
}

function HtmlCommentMessage({ comment, actor, onUpdate, onDelete }: { comment: RequirementComment; actor: Actor; onUpdate: (comment: RequirementComment, content: string) => Promise<void>; onDelete: (comment: RequirementComment) => Promise<void> }) {
  const [editing, setEditing] = useState(false);
  const [value, setValue] = useState(comment.content);
  const [saving, setSaving] = useState(false);
  const deleted = Boolean(comment.deletedAt);
  const owner = !deleted && isOwner(comment, actor);
  async function save() {
    const next = value.trim();
    if (!next || saving) return;
    setSaving(true);
    try { await onUpdate(comment, next); setEditing(false); } finally { setSaving(false); }
  }
  async function remove() {
    if (!window.confirm("确定删除这条评论吗？回复会保留。")) return;
    await onDelete(comment);
  }
  return <div className={`html-comment-message${deleted ? " is-deleted" : ""}`}>
    <span className={`avatar avatar-${comment.tone}`}>{comment.initials}</span>
    <div><header><b>{deleted ? "已删除评论" : comment.author}</b>{owner ? <span className="html-comment-message-actions"><button type="button" onClick={() => setEditing(true)} title="编辑评论" aria-label="编辑评论"><Icon name="edit" /></button><button type="button" onClick={() => void remove()} title="删除评论" aria-label="删除评论"><Icon name="trash" /></button></span> : null}</header>{deleted ? <p>该评论已删除。</p> : editing ? <div className="html-comment-edit"><input value={value} onChange={(event) => setValue(event.target.value)} autoFocus onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); void save(); } if (event.key === "Escape") { setValue(comment.content); setEditing(false); } }} /><span><button type="button" onClick={() => { setValue(comment.content); setEditing(false); }}>取消</button><button type="button" disabled={!value.trim() || saving} onClick={() => void save()}>{saving ? "保存中…" : "保存"}</button></span></div> : <p>{comment.content}</p>}</div>
  </div>;
}

export function DemoCommentFrame({ viewport, src, refreshKey = 0, commentMode, comments, actor, onCommentModeChange, onCreateComment, onReply, onUpdate, onDelete }: { viewport: "desktop" | "mobile"; src: string; refreshKey?: number; commentMode: boolean; comments: RequirementComment[]; actor: Actor; onCommentModeChange: (value: boolean) => void; onCreateComment: (content: string, anchor: HtmlCommentAnchor) => Promise<RequirementComment>; onReply: (threadId: string, content: string) => Promise<RequirementComment>; onUpdate: (comment: RequirementComment, content: string) => Promise<void>; onDelete: (comment: RequirementComment) => Promise<void> }) {
  const frame = useRef<HTMLIFrameElement>(null);
  const [sourceDoc, setSourceDoc] = useState(""); const [selection, setSelection] = useState<FrameSelection | null>(null); const [text, setText] = useState(""); const [reply, setReply] = useState(""); const [sending, setSending] = useState(false); const [activeId, setActiveId] = useState<string | null>(null); const [activePosition, setActivePosition] = useState<{ left: number; top: number } | null>(null); const [hoverId, setHoverId] = useState<string | null>(null); const [hoverPosition, setHoverPosition] = useState<{ left: number; top: number } | null>(null); const [error, setError] = useState(""); const hoverTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const sendToDemo = (type: string, payload: Record<string, unknown> = {}) => frame.current?.contentWindow?.postMessage({ bridge: BRIDGE, type, ...payload }, "*");
  useEffect(() => { let alive = true; void fetch(src, { credentials: "same-origin", cache: "no-store" }).then((response) => response.ok ? response.text() : Promise.reject(new Error("Demo 页面读取失败。"))).then((html) => { if (alive) setSourceDoc(injectBridge(html, src)); }).catch(() => { if (alive) setError("当前 Demo 不是本平台可评论的 HTML 页面。"); }); return () => { alive = false; }; }, [src, refreshKey]);
  useEffect(() => { const receive = (event: MessageEvent) => { if (event.source !== frame.current?.contentWindow || !event.data || event.data.bridge !== BRIDGE) return; const data = event.data as Record<string, unknown>; if (data.type === "ready") { sendToDemo("mode", { value: commentMode }); sendToDemo("markers", { items: roots(comments).map((comment) => ({ id: comment.id, initial: comment.initials, selector: (comment.anchor as HtmlCommentAnchor).selector, quote: (comment.anchor as HtmlCommentAnchor).quote })) }); } if (data.type === "selection" && typeof data.selector === "string" && typeof data.quote === "string") { const frameRect = frame.current?.getBoundingClientRect(); if (!frameRect) return; setSelection({ anchor: { documentId: "", documentPath: "", selector: data.selector, quote: data.quote, x: Number(data.x), y: Number(data.y), width: Number(data.width), height: Number(data.height) }, left: Math.min(window.innerWidth - 292, Math.max(12, frameRect.left + Number(data.viewportLeft))), top: Math.min(window.innerHeight - 56, frameRect.top + Number(data.viewportBottom) + 10) }); setText(""); setError(""); } if (data.type === "marker-hover" && typeof data.id === "string") { if (hoverTimer.current) clearTimeout(hoverTimer.current); const frameRect = frame.current?.getBoundingClientRect(); if (!frameRect) return; const replyCount = comments.filter((comment) => comment.parentId === data.id && !comment.deletedAt).length; setHoverId(data.id); setHoverPosition(bubblePosition(frameRect, data, Math.min(360, 112 + replyCount * 56))); } if (data.type === "marker-leave") { if (hoverTimer.current) clearTimeout(hoverTimer.current); hoverTimer.current = setTimeout(() => { setHoverId(null); setHoverPosition(null); }, 180); } if (data.type === "marker-click" && typeof data.id === "string") { if (hoverTimer.current) clearTimeout(hoverTimer.current); const frameRect = frame.current?.getBoundingClientRect(); if (!frameRect) return; setHoverId(null); setHoverPosition(null); setActiveId(data.id); setActivePosition(bubblePosition(frameRect, data, 246)); } }; window.addEventListener("message", receive); return () => { window.removeEventListener("message", receive); if (hoverTimer.current) clearTimeout(hoverTimer.current); }; }, [commentMode, comments]);
  useEffect(() => { sendToDemo("mode", { value: commentMode }); }, [commentMode]);
  useEffect(() => { sendToDemo("markers", { items: roots(comments).map((comment) => ({ id: comment.id, initial: comment.initials, selector: (comment.anchor as HtmlCommentAnchor).selector, quote: (comment.anchor as HtmlCommentAnchor).quote })) }); }, [comments, sourceDoc]);
  async function saveComment() { if (!selection || !text.trim() || sending) return; setSending(true); try { await onCreateComment(text, selection.anchor); setSelection(null); setText(""); sendToDemo("clear-selection"); onCommentModeChange(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "评论保存失败。"); } finally { setSending(false); } }
  async function saveReply() { if (!activeId || !reply.trim() || sending) return; setSending(true); try { await onReply(activeId, reply); setReply(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "回复保存失败。"); } finally { setSending(false); } }
  const active = roots(comments).find((comment) => comment.id === activeId) ?? null; const replies = active ? comments.filter((comment) => comment.parentId === active.id) : []; const hovered = roots(comments).find((comment) => comment.id === hoverId) ?? null; const hoveredReplies = hovered ? comments.filter((comment) => comment.parentId === hovered.id && !comment.deletedAt) : [];
  return <div className={`demo-stage ${viewport === "mobile" ? "is-mobile" : ""}${commentMode ? " is-commenting" : ""}`}><iframe ref={frame} title="图片转采购单 Demo" className="demo-frame" sandbox="allow-scripts allow-forms" srcDoc={sourceDoc || undefined} src={sourceDoc ? undefined : src} />{selection ? <div className="html-comment-composer" style={{ left: selection.left, top: selection.top }}><span className="html-comment-avatar">{actor.initial}</span><input value={text} onChange={(event) => setText(event.target.value)} placeholder="添加评论…" autoFocus onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); void saveComment(); } if (event.key === "Escape") { setSelection(null); sendToDemo("clear-selection"); } }} /><button type="button" disabled={!text.trim() || sending} onClick={() => void saveComment()} aria-label="保存 HTML 评论">✓</button>{error ? <small>{error}</small> : null}</div> : null}{hovered && hoverPosition ? <div className="html-comment-tooltip" style={{ left: hoverPosition.left, top: hoverPosition.top }} onMouseEnter={() => { if (hoverTimer.current) clearTimeout(hoverTimer.current); }} onMouseLeave={() => { hoverTimer.current = setTimeout(() => { setHoverId(null); setHoverPosition(null); }, 180); }}><span className={`avatar avatar-${hovered.tone}`}>{hovered.initials}</span><div className="html-comment-tooltip-body"><div className="html-comment-tooltip-meta"><b>{hovered.author}</b><time>{new Date(hovered.createdAt).toLocaleDateString("zh-CN", { month: "numeric", day: "numeric" })}</time></div><p>{hovered.content}</p>{hoveredReplies.length ? <div className="html-comment-tooltip-replies">{hoveredReplies.map((item) => <div key={item.id}><span className={`avatar avatar-${item.tone}`}>{item.initials}</span><section><b>{item.author}</b><p>{item.content}</p></section></div>)}</div> : null}</div></div> : null}{active && activePosition ? <div className="html-comment-thread" style={activePosition}><header><span>{(active.anchor as HtmlCommentAnchor).quote}</span><button type="button" onClick={() => { setActiveId(null); setActivePosition(null); }} aria-label="关闭 HTML 评论">×</button></header><HtmlCommentMessage comment={active} actor={actor} onUpdate={onUpdate} onDelete={onDelete} />{replies.map((item) => <HtmlCommentMessage key={item.id} comment={item} actor={actor} onUpdate={onUpdate} onDelete={onDelete} />)}<div className="html-comment-reply"><input value={reply} onChange={(event) => setReply(event.target.value)} placeholder="回复…" onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); void saveReply(); } }} /><button type="button" disabled={!reply.trim() || sending} onClick={() => void saveReply()} aria-label="发送 HTML 回复">✓</button></div></div> : null}{error && !selection ? <small className="html-comment-error">{error}</small> : null}</div>;
}
